IF DB_ID('RHU') IS NOT NULL
BEGIN
    DROP DATABASE IF EXISTS RHU;
END;
GO

IF DB_ID('RHU') IS NULL
BEGIN
    CREATE DATABASE RHU;
END;
GO

USE RHU;
GO

IF OBJECT_ID('dbo.DEPARTAMENTS') IS NOT NULL
BEGIN
    DROP TABLE IF EXISTS DEPARTAMENTS;
END;
GO

IF OBJECT_ID('dbo.DEPARTAMENTS', 'U') IS NULL
BEGIN
    CREATE TABLE DEPARTAMENTS (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        DEPARTAMENT VARCHAR(100)
    );
END;
GO

IF OBJECT_ID('dbo.EMPLOYMENTS_JOB', 'U') IS NOT NULL
BEGIN
    DROP TABLE IF EXISTS EMPLOYMENTS_JOB;
END;
GO

IF OBJECT_ID('dbo.EMPLOYMENTS_JOB', 'U') IS NULL
BEGIN
    CREATE TABLE EMPLOYMENTS_JOB (
        ID INT IDENTITY(1,1) PRIMARY KEY,
	    ID_DEPARTAMENT INT,
        TITLE VARCHAR(100),
        SALARY DECIMAL(10,2),
        STATUS VARCHAR(30),
        CONSTRAINT FK_ID_DEPARTAMENT_IBFK1 FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENTS(ID) ON DELETE CASCADE
    );
END;
GO

IF OBJECT_ID('dbo.CANDIDATES', 'U') IS NOT NULL
BEGIN
    DROP TABLE IF EXISTS CANDIDATES;
END;
GO

IF OBJECT_ID('dbo.CANDIDATES', 'U') IS NULL
BEGIN
    CREATE TABLE CANDIDATES (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        NAME VARCHAR(100),
        EMAIL VARCHAR(100),
        TELEPHONE VARCHAR(20),
        CITY VARCHAR(80)
    );
END;
GO

IF OBJECT_ID('dbo.SELECTION_PROCESS', 'U') IS NOT NULL
BEGIN
    DROP TABLE IF EXISTS SELECTION_PROCESS;
END;
GO

IF OBJECT_ID('dbo.SELECTION_PROCESS', 'U') IS NULL
BEGIN
    CREATE TABLE SELECTION_PROCESS (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        ID_CANDIDATE INT,
        ID_EMPLOYMENT_JOB INT,
        STEP VARCHAR(50),
        STATUS VARCHAR(30),
        DATE_SELECTION_PROCESS DATE,
        CONSTRAINT FK_ID_CANDIDATE_IBFK2 FOREIGN KEY (ID_CANDIDATE) REFERENCES CANDIDATES(ID) ON DELETE CASCADE,
        CONSTRAINT FK_ID_EMPLOYMENT_JOB_IBFK1 FOREIGN KEY (ID_EMPLOYMENT_JOB) REFERENCES EMPLOYMENTS_JOB(ID) ON DELETE CASCADE
    );
END;
GO

IF OBJECT_ID('dbo.EMPLOYEES', 'U') IS NOT NULL
BEGIN
    DROP TABLE IF EXISTS EMPLOYEES;
END;
GO

IF OBJECT_ID('dbo.EMPLOYEES', 'U') IS NULL
BEGIN
    CREATE TABLE EMPLOYEES (
        ID INT IDENTITY(1,1) PRIMARY KEY,
	    ID_DEPARTAMENT INT,
        NAME VARCHAR(100),
        EMAIL VARCHAR(100),
        TELEPHONE VARCHAR(20),
        CITY VARCHAR(80),
        POSITION VARCHAR(100),
        SALARY DECIMAL(10,2),
        DATE_CONTRATATION DATE,
        CONSTRAINT FK_ID_DEPARTAMENT_IBFK2 FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENTS(ID) ON DELETE CASCADE
    );
END;
GO

INSERT INTO DEPARTAMENTS (DEPARTAMENT) VALUES ('TI - Tecnologia da Informação');
INSERT INTO DEPARTAMENTS (DEPARTAMENT) VALUES ('RH - Recursos Humanos');
INSERT INTO DEPARTAMENTS (DEPARTAMENT) VALUES ('FIN - Financeiro');
INSERT INTO DEPARTAMENTS (DEPARTAMENT) VALUES ('COM - Comercial');
INSERT INTO DEPARTAMENTS (DEPARTAMENT) VALUES ('OPS - Operações');
INSERT INTO DEPARTAMENTS (DEPARTAMENT) VALUES ('JUR - Jurídico');
INSERT INTO DEPARTAMENTS (DEPARTAMENT) VALUES ('DIR - Diretoria');
INSERT INTO DEPARTAMENTS (DEPARTAMENT) VALUES ('MKT - Marketing');

INSERT INTO EMPLOYMENTS_JOB (ID_DEPARTAMENT, TITLE, SALARY, STATUS) VALUES (1, 'Assistente de TI', 2200.00, 'ABERTO');
INSERT INTO EMPLOYMENTS_JOB (ID_DEPARTAMENT, TITLE, SALARY, STATUS) VALUES (2, 'Auxiliar de RH', 1600.00, 'ABERTO');
INSERT INTO EMPLOYMENTS_JOB (ID_DEPARTAMENT, TITLE, SALARY, STATUS) VALUES (3, 'Especialista Financeiro', 5800.00, 'ABERTO');
INSERT INTO EMPLOYMENTS_JOB (ID_DEPARTAMENT, TITLE, SALARY, STATUS) VALUES (4, 'Coordenador de Vendas', 6500.00, 'ABERTO');
INSERT INTO EMPLOYMENTS_JOB (ID_DEPARTAMENT, TITLE, SALARY, STATUS) VALUES (5, 'Gerente de Operações', 8300.00, 'ABERTO');
INSERT INTO EMPLOYMENTS_JOB (ID_DEPARTAMENT, TITLE, SALARY, STATUS) VALUES (6, 'Analista Jurídico', 3400.00, 'ABERTO');
INSERT INTO EMPLOYMENTS_JOB (ID_DEPARTAMENT, TITLE, SALARY, STATUS) VALUES (7, 'Diretor Administrativo', 19000.00, 'ABERTO');
INSERT INTO EMPLOYMENTS_JOB (ID_DEPARTAMENT, TITLE, SALARY, STATUS) VALUES (8, 'Estágio em Marketing', 900.00, 'ABERTO');

INSERT INTO CANDIDATES (NAME, EMAIL, TELEPHONE, CITY) VALUES ('Ana Souza', 'ana.souza@rhu.com.br', '11999990001', 'São Paulo');
INSERT INTO CANDIDATES (NAME, EMAIL, TELEPHONE, CITY) VALUES ('Bruno Lima', 'bruno.lima@rhu.com.br', '11999990002', 'Campinas');
INSERT INTO CANDIDATES (NAME, EMAIL, TELEPHONE, CITY) VALUES ('Carla Mendes', 'carla.mendes@rhu.com.br', '11999990003', 'Santos');
INSERT INTO CANDIDATES (NAME, EMAIL, TELEPHONE, CITY) VALUES ('Diego Alves', 'diego.alves@rhu.com.br', '11999990004', 'Sorocaba');
INSERT INTO CANDIDATES (NAME, EMAIL, TELEPHONE, CITY) VALUES ('Eduarda Rocha', 'eduarda.rocha@rhu.com.br', '11999990005', 'São Paulo');
INSERT INTO CANDIDATES (NAME, EMAIL, TELEPHONE, CITY) VALUES ('Felipe Gomes', 'felipe.gomes@rhu.com.br', '11999990006', 'Guarulhos');
INSERT INTO CANDIDATES (NAME, EMAIL, TELEPHONE, CITY) VALUES ('Gabriela Costa', 'gabriela.costa@rhu.com.br', '11999990007', 'Osasco');
INSERT INTO CANDIDATES (NAME, EMAIL, TELEPHONE, CITY) VALUES ('Henrique Nunes', 'henrique.nunes@rhu.com.br', '11999990008', 'Jundiaí');
INSERT INTO CANDIDATES (NAME, EMAIL, TELEPHONE, CITY) VALUES ('Isabela Martins', 'isabela.martins@rhu.com.br', '11999990009', 'Barueri');
INSERT INTO CANDIDATES (NAME, EMAIL, TELEPHONE, CITY) VALUES ('João Pereira', 'joao.pereira@rhu.com.br', '11999990010', 'São Paulo');

INSERT INTO SELECTION_PROCESS (ID_CANDIDATE, ID_EMPLOYMENT_JOB, STEP, STATUS, DATE_SELECTION_PROCESS) VALUES (1, 1, 'ENTREVISTA FINAL', 'CONTRATADO', '2026-06-01');
INSERT INTO SELECTION_PROCESS (ID_CANDIDATE, ID_EMPLOYMENT_JOB, STEP, STATUS, DATE_SELECTION_PROCESS) VALUES (2, 1, 'TESTE TÉCNICO', 'EM ANDAMENTO', '2026-06-02');
INSERT INTO SELECTION_PROCESS (ID_CANDIDATE, ID_EMPLOYMENT_JOB, STEP, STATUS, DATE_SELECTION_PROCESS) VALUES (3, 2, 'ENTREVISTA INICIAL', 'CONTRATADO', '2026-06-03');
INSERT INTO SELECTION_PROCESS (ID_CANDIDATE, ID_EMPLOYMENT_JOB, STEP, STATUS, DATE_SELECTION_PROCESS) VALUES (4, 3, 'TRIAGEM', 'FINALIZADO', '2026-06-04');
INSERT INTO SELECTION_PROCESS (ID_CANDIDATE, ID_EMPLOYMENT_JOB, STEP, STATUS, DATE_SELECTION_PROCESS) VALUES (5, 4, 'ENTREVISTA GESTOR', 'CONTRATADO', '2026-06-05');
INSERT INTO SELECTION_PROCESS (ID_CANDIDATE, ID_EMPLOYMENT_JOB, STEP, STATUS, DATE_SELECTION_PROCESS) VALUES (6, 5, 'TESTE PRÁTICO', 'EM ANDAMENTO', '2026-06-06');
INSERT INTO SELECTION_PROCESS (ID_CANDIDATE, ID_EMPLOYMENT_JOB, STEP, STATUS, DATE_SELECTION_PROCESS) VALUES (7, 3, 'ENTREVISTA FINAL', 'CONTRATADO', '2026-06-07');
INSERT INTO SELECTION_PROCESS (ID_CANDIDATE, ID_EMPLOYMENT_JOB, STEP, STATUS, DATE_SELECTION_PROCESS) VALUES (8, 2, 'TRIAGEM', 'FINALIZADO', '2026-06-08');
INSERT INTO SELECTION_PROCESS (ID_CANDIDATE, ID_EMPLOYMENT_JOB, STEP, STATUS, DATE_SELECTION_PROCESS) VALUES (9, 4, 'ENTREVISTA INICIAL', 'EM ANDAMENTO', '2026-06-09');
INSERT INTO SELECTION_PROCESS (ID_CANDIDATE, ID_EMPLOYMENT_JOB, STEP, STATUS, DATE_SELECTION_PROCESS) VALUES (10, 5, 'ENTREVISTA FINAL', 'CONTRATADO', '2026-06-10');

INSERT INTO EMPLOYEES (
    ID_DEPARTAMENT,
    NAME,
    EMAIL,
    TELEPHONE,
    CITY,
    POSITION,
    SALARY,
    DATE_CONTRATATION
)
SELECT
    EMPLOYMENTS_JOB.ID_DEPARTAMENT,
    CANDIDATES.NAME,
    CANDIDATES.EMAIL,
    CANDIDATES.TELEPHONE,
    CANDIDATES.CITY,
    EMPLOYMENTS_JOB.TITLE,
    EMPLOYMENTS_JOB.SALARY,
    GETDATE()
FROM SELECTION_PROCESS
INNER JOIN CANDIDATES
    ON CANDIDATES.ID = SELECTION_PROCESS.ID_CANDIDATE
INNER JOIN EMPLOYMENTS_JOB
    ON EMPLOYMENTS_JOB.ID = SELECTION_PROCESS.ID_EMPLOYMENT_JOB
WHERE SELECTION_PROCESS.STATUS = 'CONTRATADO';