-- USE
USE 'database_name';

-- SET SQL_SAFE_UPDATES - 1175
SET SQL_SAFE_UPDATES = 0;

-- SELECT VERSION()
SELECT VERSION();

-- LIST ALL CONSTRAINTS DEFINED FOR TABLE
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = 'database_name' AND TABLE_NAME = 'table_name';

-- LIST ALL TABLE COLUMNS THAT ARE FOREIGN KEYS AND THEIR REFERENCED TABLES/COLUMNS
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'database_name' AND TABLE_NAME = 'table_name' AND REFERENCED_TABLE_NAME IS NOT NULL;

-- SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'table_name' ORDER BY ORDINAL_POSITION;

-- EXPLAIN SELECT
EXPLAIN SELECT * FROM 'table_name' WHERE 'column_name' = 'name_data';
