-- 1:1 - ONE TO ONE
SELECT
    A.COLUMN1,
	B.COLUMN2
FROM TABLE1 A
INNER JOIN TABLE2 B
    ON A.ID_PRIMARY_KEY = B.ID_FOREIGN_KEY;
	
-- N:N - MANY TO MANY
SELECT
    A.COLUMN1,
    B.COLUMN2
FROM TABLE1 A
INNER JOIN TABLE2 INTERMEDIATE
    ON INTERMEDIATE.ID_FOREIGN_KEY_TABLE1 = A.ID_PRIMARY_KEY
INNER JOIN TABLE3 B
    ON INTERMEDIATE.ID_FOREIGN_KEY_TABLE3 = B.ID_PRIMARY_KEY;